# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extuser', '0002_auto_20170922_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='firstname',
            field=models.CharField(max_length=40, verbose_name=b'First name'),
        ),
        migrations.AlterField(
            model_name='extuser',
            name='lastname',
            field=models.CharField(max_length=40, verbose_name=b'Last name'),
        ),
    ]
