# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_manufacturers'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturers',
            name='city',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='country',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='mail',
            field=models.EmailField(default='blank@blank.com', max_length=254),
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='phone',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='manufacturers',
            name='site',
            field=models.URLField(default='blank.com', max_length=32),
        ),
    ]
