# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20170816_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=64)),
                ('autonomous_power', models.BooleanField(default=True)),
                ('person_incharge', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='equipment.Users')),
            ],
        ),
    ]
