# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='power_wt',
            field=models.IntegerField(default=0),
        ),
    ]
