# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_room_caution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='plan',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/plan/%Y/%m/%d'),
        ),
    ]
