# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_rooms_power_wt'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(default='', max_length=32),
        ),
    ]
