# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_auto_20170926_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='plan',
            field=models.ImageField(null=True, upload_to='rooms/plan/%Y/%m/%d'),
        ),
    ]
