# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_rooms_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('inv_number', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('ser_number', models.CharField(max_length=32)),
                ('name_ru', models.CharField(max_length=128)),
                ('name_en', models.CharField(max_length=128)),
            ],
        ),
    ]
