# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_auto_20171005_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('name', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='rooms/hazard/%Y/%m/%d')),
            ],
        ),
    ]
