# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_equipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='manual',
            field=models.FileField(default=0, upload_to=b''),
        ),
        migrations.AddField(
            model_name='equipments',
            name='photo',
            field=models.FileField(default=0, upload_to=b''),
        ),
        migrations.AddField(
            model_name='equipments',
            name='room',
            field=models.ForeignKey(max_length=5, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.Rooms'),
        ),
    ]
