# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_auto_20170816_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='last_service',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='equipments',
            name='manufacturer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='equipment.Manufacturers'),
        ),
        migrations.AddField(
            model_name='equipments',
            name='next_service',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='equipments',
            name='person_incharge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='equipment.Users'),
        ),
        migrations.AddField(
            model_name='equipments',
            name='power_wt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipments',
            name='service',
            field=models.BooleanField(default=True),
        ),
    ]
