# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_hazard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='caution',
        ),
        migrations.AddField(
            model_name='room',
            name='caution',
            field=models.ManyToManyField(null=True, to='equipment.Hazard'),
        ),
    ]
