# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_auto_20171009_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='caution',
            field=models.ManyToManyField(to='equipment.Hazard'),
        ),
    ]
