# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_auto_20171009_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='caution',
        ),
    ]
