# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_remove_room_caution'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='caution',
            field=models.ManyToManyField(to='equipment.Hazard'),
        ),
    ]
