# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_room_caution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='power_wt',
        ),
        migrations.AddField(
            model_name='room',
            name='block',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='clean_room',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='electricity',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='gases',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='ventilation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='water',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
