# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_auto_20171010_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='block',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
